name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - VERSION
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read VERSION file
        id: read-version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile \
          --tag nyirsh/music-dl-helper:${{ env.VERSION }} \
          --tag nyirsh/music-dl-helper:latest

      - name: Push the Docker image
        run: |
          docker push nyirsh/music-dl-helper:${{ env.VERSION }}
          docker push nyirsh/music-dl-helper:latest
